FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore ProbMind.sln
RUN dotnet publish ProbMind.Worker/ProbMind.Worker.csproj -c Release -o /app/publish --no-restore
RUN test -f /app/publish/Microsoft.EntityFrameworkCore.Relational.dll

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ProbMind.Worker.dll"]
